[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/2WCbZ8YpmuPxUtM6PzbFOfY5k4B"
arbitrum_sepolia = "https://arbitrum-sepolia.infura.io/v3/2WCbZ8YpmuPxUtM6PzbFOfY5k4B" 

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000